"use strict";
const fs=require("fs");
const path=require("path");
const root=path.resolve(__dirname,"..");
const field=(label,name,type="text",extra="")=>`<label>${label}<input name="${name}" type="${type}" ${extra}></label>`;
const area=(label,name)=>`<label class="qcb-full">${label}<textarea name="${name}" rows="4"></textarea></label>`;
const select=(label,name,options)=>`<label>${label}<select name="${name}"><option value="">Select</option>${options.map(x=>`<option>${x}</option>`).join("")}</select></label>`;
const choices=(name,items)=>`<div class="qcb-choice-grid">${items.map(x=>`<label class="qcb-choice"><input type="checkbox" name="${name}" value="${x}">${x}</label>`).join("")}</div>`;
function shell({id,title,kicker,steps}){
 const pills=steps.map((s,i)=>`<span class="qcb-step-pill${i?"":" active"}" data-qcb-step-pill="${i+1}">${s[0]}</span>`).join("");
 const pages=steps.map((s,i)=>`<section class="qcb-step-page${i?"":" active"}" data-qcb-step="${i+1}"><h3>${s[1]}</h3>${s[2]}</section>`).join("\n");
 return `<section id="${id}" class="qcb-builder-wrap" data-qcb-builder="${id==='builder-start'?'car-finance':'cruise'}" data-qcb-version="4" aria-labelledby="${id}-title">
  <span id="${id==='builder-start'?'car-finance-tool':'cruise-builder-compat'}" aria-hidden="true"></span>
  <div class="qcb-builder qcb-framework-v1 qcb-airbnb-builder">
   <div class="qcb-builder-head"><p class="qcb-builder-kicker">Quaerens Complaint Pack Framework&trade; v1.6</p><h2 id="${id}-title">${title}</h2><p>${kicker}</p><div class="qcb-privacy"><strong>Browser-first privacy</strong><span>Your answers remain on this device unless you download, copy, print or deliberately use the separate Guided Support route.</span></div></div>
   <div class="qcb-builder-grid qcb-airbnb-shell"><form class="qcb-form qcb-airbnb-stage" autocomplete="on"><div class="qcb-save-row"><label><input type="checkbox" data-qcb-save> Save locally on this device</label><button type="button" class="qcb-btn ghost" data-qcb-clear>Delete Saved Answers</button></div><div class="qcb-progress-shell"><div class="qcb-progress-meta"><span data-qcb-step-label>Step 1 of ${steps.length}</span><span data-qcb-progress-label>${Math.round(100/steps.length)}% complete</span></div><div class="qcb-progress-track" role="progressbar" aria-label="Complaint pack progress" aria-valuemin="0" aria-valuemax="100"><span class="qcb-progress-fill" data-qcb-progress></span></div></div><div class="qcb-step-pills qcb-step-map" aria-label="Builder steps">${pills}</div><div class="qcb-step-pages">${pages}</div><div class="qcb-nav"><div class="qcb-nav-left"><button type="button" class="qcb-btn secondary" data-qcb-prev>Previous</button></div><div class="qcb-nav-right"><button type="button" class="qcb-btn" data-qcb-next>Next</button></div></div></form>
   <aside class="qcb-preview qcb-airbnb-preview" aria-label="Live professional complaint pack preview" aria-live="polite"><div class="qcb-preview-head"><div><p class="qcb-builder-kicker">Live professional preview</p><h3>Quaerens Consumer Complaint File</h3></div><span class="qcb-status" data-qcb-status>Needs key information</span></div><div class="qcb-preview-metrics"><div class="qcb-preview-metric"><strong data-qcb-evidence-score>0%</strong><span>Evidence Readiness</span></div><div class="qcb-preview-metric"><strong data-qcb-preview-total>&pound;0.00</strong><span>Estimated Total</span></div><div class="qcb-preview-metric"><strong data-qcb-route-count>0</strong><span>Routes</span></div></div><div class="qcb-page-stack" data-qcb-preview></div><p class="qcb-copy-note" data-qcb-copy-status>Preview updates after a short pause.</p></aside></div>
  </div>
 </section>`;
}
const timeline=`<p class="qcb-small">Add dated events and cross-reference supporting evidence.</p><div class="qcb-timeline-actions"><h4>Chronology events</h4><button type="button" class="qcb-btn ghost" data-qcb-add-event>Add Timeline Event</button></div><div data-qcb-timeline></div>`;
const evidence=`<div class="qcb-readiness"><strong data-qcb-readiness-title>Evidence Readiness: 0%</strong><div class="qcb-gauge"><span data-qcb-gauge></span></div><p class="qcb-small" data-qcb-readiness-copy>Your evidence position will update as you answer.</p></div><div data-qcb-evidence></div>`;
const financial=(fields)=>`${fields}<div class="qcb-timeline-actions"><h4>Additional financial losses</h4><button type="button" class="qcb-btn ghost" data-qcb-add-loss>Add Loss Row</button></div><div class="qcb-loss-table" data-qcb-losses></div><div class="qcb-money-cards"><div class="qcb-money-card"><strong data-qcb-booking-total>&pound;0.00</strong><span>Primary position</span></div><div class="qcb-money-card"><strong data-qcb-extra-total>&pound;0.00</strong><span>Additional documented losses</span></div><div class="qcb-money-card"><strong data-qcb-total-requested>&pound;0.00</strong><span>Estimated financial position</span></div></div>`;
const pack=(product)=>`<div class="qcb-ready-banner"><div class="qcb-ready-icon" aria-hidden="true">&#10003;</div><div class="qcb-ready-copy"><span>Complaint Pack Ready</span><strong data-qcb-final-status>Complete the key facts to strengthen your pack</strong></div></div><h3>Generate your professional ${product}</h3><div class="qcb-quality"><div class="qcb-quality-head"><span>Complaint Pack Quality</span><strong data-qcb-quality-score>0%</strong></div><div class="qcb-quality-track" role="progressbar" aria-label="Complaint Pack organisation and completeness" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><span data-qcb-quality-bar></span></div><p data-qcb-quality-copy>Complete the core case details.</p></div><div class="qcb-download-grid"><button type="button" class="qcb-btn" data-qcb-download-pdf>Download PDF</button><button type="button" class="qcb-btn" data-qcb-download-word>Download Word</button><button type="button" class="qcb-btn" data-qcb-download-txt>Download TXT</button><button type="button" class="qcb-btn secondary" data-qcb-copy-letter>Copy Complaint Letter</button><button type="button" class="qcb-btn secondary" data-qcb-copy-email>Copy Cover Email</button><button type="button" class="qcb-btn secondary" data-qcb-print>Print</button></div><div class="qcb-final-grid"><div><span>Evidence Readiness</span><strong data-qcb-final-evidence>0%</strong></div><div><span>Estimated Financial Position</span><strong data-qcb-final-total>&pound;0.00</strong></div><div><span>Documents Generated</span><strong>12-page pack</strong></div><div><span>Recommended Next Step</span><strong data-qcb-final-next>Complete the key facts</strong></div></div><div class="qcb-support-card" id="request-guided-support"><strong>Optional Guided Support</strong><p>This builder creates no CRM record. Guided Support is separate and passes through the Quaerens Intake Gateway.</p><a class="qcb-btn secondary" href="intake-gateway.html">Open Guided Support</a></div>`;

const car=shell({id:"builder-start",title:"Free Car Finance Compensation Complaint Pack Builder&trade;",kicker:"Organise the agreement, vehicle, sales process, commission position, affordability concerns, evidence and lender complaint in one professional file.",steps:[
 ["Agreement","Agreement, lender and vehicle",`<div class="qcb-field-grid qcb-form-grid">${field("Finance provider","lender")}${field("Dealer or broker","dealer")}${field("Agreement reference","agreementRef")}${select("Agreement type","agreementType",["Personal Contract Purchase (PCP)","Hire Purchase (HP)","Conditional sale","Personal loan","Lease / Personal Contract Hire","Other / unsure"])}${select("Agreement status","agreementStatus",["Active","Settled","Voluntarily terminated","Vehicle returned","In arrears or default","Repossessed","Unsure"])}${field("Agreement date","agreementDate","date")}${field("Vehicle make","vehicleMake")}${field("Vehicle model","vehicleModel")}${field("Vehicle registration","vehicleReg")}${field("Vehicle year","vehicleYear","number")}${field("Vehicle cash price (&pound;)","cashPrice","number","min=\"0\" step=\"0.01\"")}${field("Purchase date","purchaseDate","date")}</div>`],
 ["Finance","Finance figures",`<div class="qcb-field-grid qcb-form-grid">${field("Cash deposit (&pound;)","cashDeposit","number","min=\"0\" step=\"0.01\"")}${field("Part-exchange allowance (&pound;)","partExchangeAllowance","number","min=\"0\" step=\"0.01\"")}${field("Part-exchange settlement (&pound;)","partExchangeSettlement","number","min=\"0\" step=\"0.01\"")}${field("Dealer contribution (&pound;)","dealerContribution","number","min=\"0\" step=\"0.01\"")}${field("Amount of credit (&pound;)","amountCredit","number","min=\"0\" step=\"0.01\"")}${field("APR (%)","apr","number","min=\"0\" step=\"0.01\"")}${field("Flat rate (%)","flatRate","number","min=\"0\" step=\"0.01\"")}${field("Term (months)","termMonths","number","min=\"0\"")}${field("Monthly payment (&pound;)","monthlyPayment","number","min=\"0\" step=\"0.01\"")}${field("Number of regular payments","regularPayments","number","min=\"0\"")}${field("Final or balloon payment (&pound;)","finalPayment","number","min=\"0\" step=\"0.01\"")}${field("Total amount payable (&pound;)","totalPayable","number","min=\"0\" step=\"0.01\"")}${field("Option fee (&pound;)","optionFee","number","min=\"0\" step=\"0.01\"")}${field("Arrangement and other fees (&pound;)","arrangementFee","number","min=\"0\" step=\"0.01\"")}${field("Payments made count","paymentsMadeCount","number","min=\"0\"")}${field("Settlement amount (&pound;)","settlementAmount","number","min=\"0\" step=\"0.01\"")}${field("Arrears charges (&pound;)","arrearsCharges","number","min=\"0\" step=\"0.01\"")}${field("Refunds received (&pound;)","refundsReceived","number","min=\"0\" step=\"0.01\"")}</div>`],
 ["Sale","Sale, suitability and concerns",`${choices("issue",["Commission was not clearly explained","Possible discretionary commission arrangement","High or unclear commission","Affordability concerns","Unsuitable recommendation","Misrepresentation","Rushed or pressured sale","Fees, settlement or termination issue","Vehicle return or repossession issue","Missing agreement or information"])}<div class="qcb-field-grid qcb-form-grid">${select("Alternatives discussed?","alternativesDiscussed",["Yes","No","Unsure"])}${select("Best or only option presented?","bestOnlyOption",["Yes","No","Unsure"])}${select("Adequate explanation provided?","adequateExplanation",["Yes","No","Unsure"])}${select("Pressured or rushed?","pressured",["Yes","No","Unsure"])}${area("Factual account of the sale and recommendation","saleNarrative")}${area("Other concerns","otherConcern")}</div>`],
 ["Commission","Commission, disclosures and response",`<div class="qcb-field-grid qcb-form-grid">${select("Commission explained?","commissionExplained",["Yes","No","Unsure","Not applicable"])}${select("Commission amount disclosed?","commissionAmountDisclosed",["Yes","No","Unsure","Not applicable"])}${select("Calculation method disclosed?","commissionMethodDisclosed",["Yes","No","Unsure","Not applicable"])}${select("Potential rate influence explained?","commissionAffectRate",["Yes","No","Unsure","Not applicable"])}${select("Lender confirmed commission?","lenderConfirmedCommission",["Yes","No","Unsure"])}${field("Verified commission amount (&pound;)","commissionAmount","number","min=\"0\" step=\"0.01\"")}${field("Verified commission percentage","commissionPercentage","number","min=\"0\" step=\"0.01\"")}${field("Commission type","commissionType")}${field("Commission recipient","commissionRecipient")}${field("Official lender redress figure (&pound;)","officialRedressFigure","number","min=\"0\" step=\"0.01\"")}${field("Entered compensatory interest (&pound;)","compensatoryInterest","number","min=\"0\" step=\"0.01\"")}${field("Source document","commissionSource")}${field("Complaint reference","complaintRef")}${field("Complaint status","complaintStatus")}${area("Lender response","responseSummary")}${area("Requested outcome","requestedOutcome")}</div>`],
 ["Timeline","Detailed timeline",timeline],["Evidence","Evidence Readiness",evidence],["Financial","Financial schedule",financial(choices("route",["Finance provider formal complaint","Dealer or broker information request","Financial Ombudsman Service after final response","Other official route"]))],["Pack","Generate pack",pack("Car Finance Complaint Pack")]
]});

const cruise=shell({id:"cruise-builder",title:"Free Cruise Compensation Complaint Pack Builder&trade;",kicker:"Organise the booking, itinerary, cabin, facilities, excursions, baggage, financial impact and responses in one evidence-first file.",steps:[
 ["Booking","Cruise and booking details",`<div class="qcb-field-grid qcb-form-grid">${field("Cruise line","cruiseLine")}${field("Ship name","shipName")}${field("Organiser or tour operator","organiserName")}${field("Intermediary or travel agent","intermediaryName")}${field("Booking reference","bookingReference")}${select("Booking type","bookingType",["Cruise-only direct","Package holiday","Fly-cruise package","Travel-agent booking","Other / unsure"])}${select("Payment route","paymentRoute",["Direct to cruise line","Organiser or tour operator","Travel agent","Credit card","Debit card","Other / unsure"])}${field("Booking date","bookingDate","date")}${field("Departure date","departureDate","date")}${field("Return date","returnDate","date")}${field("Departure port","departurePort")}${field("Return port","returnPort")}${field("Primary passenger","primaryPassengerName")}${field("All passenger names","passengerNames")}${field("Passenger count","passengerCount","number","min=\"1\"")}</div>`],
 ["Itinerary","Itinerary and disruption",`${choices("issue",["Cancellation","Major itinerary change","Missed port","Shortened voyage","Delayed departure","Delayed return","Denied boarding","Cabin defect or downgrade","Hygiene or sanitation concern","Accessibility failure","Missing facilities","Excursion problem","Baggage issue","Extra charge or refund dispute"])}<div class="qcb-field-grid qcb-form-grid">${area("Planned itinerary","plannedItinerary")}${area("Actual itinerary","actualItinerary")}${area("Itinerary change or missed-port details","itineraryChangeNotes")}${area("Summary of what happened","issueSummary")}</div>`],
 ["On board","Cabin, facilities and excursions",`<div class="qcb-field-grid qcb-form-grid">${field("Cabin booked","cabinBooked")}${field("Cabin received","cabinReceived")}${area("Cabin defects, hygiene, sanitation, facilities or accessibility","cabinIssues")}${field("Excursion booked through","excursionBookedBy")}${area("Excursion problems","excursionDetails")}${area("Baggage or property issues","baggageDetails")}${area("Medical, accessibility or urgent concerns","urgentNotes")}</div>`],
 ["Complaint","Complaint and requested outcome",`<div class="qcb-field-grid qcb-form-grid">${field("Problem date","problemDate","date")}${field("Complaint date","complaintDate","date")}${field("Response date","responseDate","date")}${area("Response received","responseSummary")}${area("Requested outcome","requestedOutcome")}${area("Additional outcome notes","outcomeNotes")}</div>`],
 ["Timeline","Detailed timeline",timeline],["Evidence","Evidence Readiness",evidence],["Financial","Financial schedule",financial(`<div class="qcb-field-grid qcb-form-grid">${field("Cruise price paid (&pound;)","cruisePricePaid","number","min=\"0\" step=\"0.01\"")}${field("Cash refund received (&pound;)","refundReceived","number","min=\"0\" step=\"0.01\"")}${field("Future cruise credit (&pound;)","futureCruiseCreditValue","number","min=\"0\" step=\"0.01\"")}${field("Replacement travel/accommodation (&pound;)","replacementCosts","number","min=\"0\" step=\"0.01\"")}${field("Excursion costs (&pound;)","excursionCosts","number","min=\"0\" step=\"0.01\"")}${field("Baggage/property costs (&pound;)","propertyCosts","number","min=\"0\" step=\"0.01\"")}${field("Medical/accessibility costs (&pound;)","medicalCosts","number","min=\"0\" step=\"0.01\"")}${field("Other documented costs (&pound;)","otherCosts","number","min=\"0\" step=\"0.01\"")}${area("Financial notes","financialNotes")}</div>${choices("route",["Cruise line complaint","Organiser or package-travel complaint","Travel agent or intermediary","Payment provider","Travel insurer","Other official route"])}`)],["Pack","Generate pack",pack("Cruise Compensation Complaint Pack")]
]});

function migrateCar(){const file=path.join(root,"public/car-finance.html");let html=fs.readFileSync(file,"utf8");if(!html.includes('framework-v1-builder.css'))html=html.replace('</head>','  <link rel="stylesheet" href="/complaint-builder/styles/framework-v1-builder.css?v=20260806-v1-6">\n</head>');const start=html.indexOf('<div id="builder-start"');const marker='<section class="section pt-0">\n      <div class="section-wrap">\n        <div class="info-box">\n          <h2 class="text-3xl font-extrabold mb-5">Car finance topics explained</h2>';if(start<0||html.indexOf(marker,start)<0)throw new Error('Car Finance builder boundaries not found');const end=html.indexOf(marker,start);html=html.slice(0,start)+car+'\n        </div>\n      </div>\n    </section>\n\n    '+html.slice(end);const legacy=html.indexOf('<script>\n    const CAR_FINANCE_STATUS_CONFIG');if(legacy>=0){const close=html.indexOf('</script>',legacy);html=html.slice(0,legacy)+html.slice(close+9);}html=html.replace('</body>',`  <script src="/complaint-builder/config/framework-a-categories-v1.4.js?v=1.6.0" defer></script>\n  <script src="/complaint-builder/adapters/framework-a-category-adapters-v1.6.js?v=1.6.0" defer></script>\n  <script src="/complaint-builder/adapters/framework-a-car-finance-adapter-v1.6.js?v=1.6.0" defer></script>\n  <script src="/complaint-builder/components/applicant-details.js?v=1.2.2" defer></script>\n  <script src="/airbnb-complaint-pack-v3.js?v=1.6.0" defer></script>\n</body>`);fs.writeFileSync(file,html);}
function migrateCruise(){const file=path.join(root,"public/cruise-compensation-recovery.html");let html=fs.readFileSync(file,"utf8");if(!html.includes('framework-v1-builder.css'))html=html.replace('</head>','  <link rel="stylesheet" href="/complaint-builder/styles/framework-v1-builder.css?v=20260806-v1-6">\n</head>');const start=html.indexOf('<div id="cruise-builder"');const marker='      <div class="section">\n        <h2>Official and Authoritative Resources</h2>';if(start<0||html.indexOf(marker,start)<0)throw new Error('Cruise builder boundaries not found');const end=html.indexOf(marker,start);html=html.slice(0,start)+cruise+'\n\n'+html.slice(end);const firstLegacy=html.indexOf('  <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf');if(firstLegacy>=0){const body=html.indexOf('</body>',firstLegacy);html=html.slice(0,firstLegacy)+html.slice(body);}html=html.replace('</body>',`  <script src="/complaint-builder/config/framework-a-categories-v1.4.js?v=1.6.0" defer></script>\n  <script src="/complaint-builder/adapters/framework-a-category-adapters-v1.6.js?v=1.6.0" defer></script>\n  <script src="/complaint-builder/adapters/framework-a-cruise-adapter-v1.6.js?v=1.6.0" defer></script>\n  <script src="/complaint-builder/components/applicant-details.js?v=1.2.2" defer></script>\n  <script src="/airbnb-complaint-pack-v3.js?v=1.6.0" defer></script>\n</body>`);fs.writeFileSync(file,html);}
migrateCar();migrateCruise();
