"use strict";

const fs = require("fs");
const path = require("path");

const id = process.argv[2];
if (!id) {
  console.error("Usage: node tools/create-builder.js <builder-id>");
  process.exit(1);
}

if (!/^[a-z0-9-]+$/.test(id)) {
  console.error("Builder id must use lowercase letters, numbers and hyphens.");
  process.exit(1);
}

const root = path.resolve(__dirname, "..", "public", "builders", id);
if (fs.existsSync(root)) {
  console.error("Builder already exists: " + root);
  process.exit(1);
}

fs.mkdirSync(root, { recursive: true });

const title = id.split("-").map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(" ");
const files = {
  [`${id}.config.js`]: `"use strict";\n\nmodule.exports = {\n  id: "${id}",\n  productName: "${title} Complaint Pack Builder",\n  shortName: "${title}",\n  pageTitle: "${title} Complaint Pack Builder | Quaerens",\n  h1: "Build Your ${title} Complaint Pack",\n  canonicalUrl: "https://www.quaerens.co.uk/${id}.html",\n  storageNamespace: "${id}",\n  schemaVersion: 1,\n  frameworkVersion: "QCBF 1.1",\n  packPrefix: "QC",\n  stages: [\n    { id: "start", label: "Start" },\n    { id: "details", label: "Details" },\n    { id: "evidence", label: "Evidence" },\n    { id: "review", label: "Review" },\n    { id: "ready", label: "Ready" }\n  ],\n  essentialFields: []\n};\n`,
  [`${id}.questions.js`]: `"use strict";\n\nmodule.exports = { questions: [] };\n`,
  [`${id}.analysis.js`]: `"use strict";\n\nfunction analyse(data) {\n  return { data: data || {}, issues: [], evidence: [], confidenceSignals: [] };\n}\n\nmodule.exports = { analyse };\n`,
  [`${id}.documents.js`]: `"use strict";\n\nconst { complaintPack, heading, paragraph } = require(\"../../complaint-builder\");\n\nfunction buildDocument(data) {\n  return complaintPack({ title: \"Quaerens Consumer Complaint File\" }, [\n    heading(\"Complaint Summary\", 1),\n    paragraph(\"Builder document content goes here.\")\n  ]);\n}\n\nmodule.exports = { buildDocument };\n`,
  [`${id}.resources.js`]: `"use strict";\n\nmodule.exports = { resources: [] };\n`,
  [`${id}.submission.js`]: `"use strict";\n\nfunction resolveSubmissionRoute() {\n  return { status: \"manual-review\", preferredMethod: \"Review the official complaint route\" };\n}\n\nmodule.exports = { resolveSubmissionRoute };\n`,
  [`${id}.page.js`]: `"use strict";\n\n(function(root) {\n  root.${camel(id)}Builder = root.${camel(id)}Builder || {};\n})(typeof globalThis !== \"undefined\" ? globalThis : window);\n`,
  [`${id}.test.js`]: `"use strict";\n\nconst assert = require(\"assert\");\nconst config = require(\"./${id}.config\");\n\nassert.strictEqual(config.id, \"${id}\");\nconsole.log(\"${title} builder scaffold tests passed\");\n`,
  "README.md": `# ${title} Builder\n\nGenerated by QCBF 1.1 scaffold.\n\nFill in config, questions, analysis, documents, resources, submission, page wiring and tests before public launch.\n`
};

Object.entries(files).forEach(([name, content]) => fs.writeFileSync(path.join(root, name), content, "utf8"));

console.log("Created builder scaffold: " + root);

function camel(value) {
  return value.replace(/(^|-)([a-z0-9])/g, (_, __, char) => char.toUpperCase());
}
